# Generated by Django 3.1 on 2021-10-07 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('post_code', models.CharField(max_length=10)),
                ('business_size', models.CharField(choices=[('1 - 5 employees', '1 - 5 employees'), ('6 - 10 employees', '6 - 10 employees'), ('10+ employees', '10+ employees')], max_length=100)),
                ('abn_number', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=100)),
                ('driver_license', models.ImageField(upload_to='contractor/license')),
                ('image', models.ImageField(upload_to='contractor/images')),
                ('insurence', models.ImageField(upload_to='contractor/insurence')),
                ('bank_name', models.CharField(max_length=100)),
                ('bsb_number', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
